name: Code Formatting Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  format-check:
    name: Prettier Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: auto-kol/agent

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: 'auto-kol/agent/yarn.lock'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Check Formatting
        run: yarn prettier --check "src/**/*.ts"
